#!/usr/bin/python3

import libvirt
conn = libvirt.open()

def state(s):
    sw = {
        libvirt.VIR_DOMAIN_NOSTATE: 'none',
        libvirt.VIR_DOMAIN_RUNNING: 'running',
        libvirt.VIR_DOMAIN_BLOCKED: 'blocked',
        libvirt.VIR_DOMAIN_PAUSED: 'paused',
        libvirt.VIR_DOMAIN_SHUTDOWN: 'shutdown',
        libvirt.VIR_DOMAIN_SHUTOFF: 'shutoff',
        libvirt.VIR_DOMAIN_CRASHED: 'crashed',
        libvirt.VIR_DOMAIN_PMSUSPENDED: 'suspended',
    }
    return sw.get(s[0], "unknown")

def first(d):
    return list(d.values())[0]

for domain in conn.listAllDomains():
    #metadata = domain.metadata(libvirt.VIR_DOMAIN_METADATA_ELEMENT, "http://spinup.io/instance")
    print(domain)
    print(domain.state())
    if domain.state() == libvirt.VIR_DOMAIN_RUNNING:
        nics = domain.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE)
        if len(nics) > 0:
            nic = first(nics)
            adr = nic['addrs'][0]['addr']
            print(domain.name(),state(domain.state()), adr)
        else:
            print(domain.name(),state(domain.state()))
